### ISSUE TITLE
JetBrains or HumbleUI?

### ISSUE THREAD

**Issue by igr** [HumbleUI/Skija#10]
Huh, is this active repo or I should go with the Jetbrains? So confused.

**Comment by tonsky** [comment]
Yes. Sorry about the confusion

**Comment by davidbruce** [comment]
Any chance the JetBrain's repo could be archived? I noticed that activity had slowed on their repo and I found the HumbleUI repo through your GitHub activity. I think this could cause a lot of confusion and lower adoption.  

~Side note: Great job on Skija!

**Comment by tonsky** [comment]
@shafirov I agree, maybe it’s time to archive JetBrains Skija fork?

**Comment by cowwoc** [comment]
@tonsky Can you please archive the old repository and point users to this one?
