### ISSUE TITLE
Allow usage of maven or gradle to build shared java code.

### ISSUE THREAD

**Issue by 0-x-2-2** [HumbleUI/Skija#20]
Allowing the usage of Maven or Gradle to build the shared code for Skija will improve how easy it is for new people to contribute to the project easier because getting the project to open in a popular Java IDE and just work is not possible without pre-processing the repo due to file structure not being standard and possibly other reasons. 

You could look at netty.io for inspiration if you want to extend the building to building cross-platform native libraries with Maven/Gradle but such tasks are usually inferior compared to the alternatives.

**Comment by tonsky** [comment]
Maven/Gradle would complicate build script a lot and add a lot of extra delay. If your goal is to open project in IDE maybe there are other ways to do it? What IDE are you talking about? Why was opening project hard?

**Comment by 0-x-2-2** [comment]
Using IntelliJ with the project outside of being a glorified text editor required defining the libraries and compiler settings manually and moving all of the java source files into a path that matches the package.

**Comment by tonsky** [comment]
I’m ready to move sources if you (or anybody else) need it and want to become a serial contributor. For example, after three PRs?

**Comment by Glavo** [comment]
I wrote a python script for generating IDEA projects, which may meet your needs.

See #35
