### ISSUE TITLE
Surface::makeImageSnapshot crashes if _nMakeImageSnapshotR returns null

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [HumbleUI/Skija#23]
`Surface::makeImageSnapshot` is correctly marked as `@Nullable` because `_nMakeImageSnapshotR` can return a null pointer. However, it doesn't check whether `_nMakeImageSnapshotR` returns null and instead always calls the `Image` constructor which will crash if the pointer is null.

**Comment by tonsky** [comment]
Thanks!
