### ISSUE TITLE
FR: Native wayland support? 

### ISSUE THREAD

**Issue by glyh** [HumbleUI/Skija#39]
Right now skija on my laptop is running through XWayland, and it's not good enough because of scaling issues. Is there a way that I can run the UI in native wayland

I'm using https://github.com/lilactown/humble-starter with `deps.edn|io.github.humbleui/humbleui|git/sha` set to 69faab0123f61c242e34061e8bcaaf772b46d0e1(lastest commit for humbeui for now).

**Comment by glyh** [comment]
This must be possible because flutter is running with native wayland on my laptop.

**Comment by dzaima** [comment]
I think what you want is JWM to have Wayland support - Skija just does graphics; and it already has an [issue for it](https://github.com/HumbleUI/JWM/issues/55), with [some recent progress](https://github.com/HumbleUI/JWM/pull/260) (though nothing near complete of course)
