### ISSUE TITLE
Add a linux arm64 build

### ISSUE THREAD

**Issue by JakeWharton** [HumbleUI/Skija#40]
I'm targeting an embedded Linux installation on an ARM device

**Comment by tonsky** [comment]
PR?

**Comment by JakeWharton** [comment]
I did take a brief look before filing the issue to see if I could, but the intricacies of the bespoke python, cmake, and of skia itself are beyond my capabilities. After all, it's why I need the wrapper in the first place!

**Comment by Glavo** [comment]
I will try to complete it in the next few months - but I can't guarantee it.

**Comment by Glavo** [comment]
One good news: It's easy to make it work. You just need to compile Skia and Skija yourself.

![image](https://user-images.githubusercontent.com/20694662/221367083-bcdbdd32-fedf-4fb9-a8ad-c96efb820736.png)

But there are still some things stopping us.

First of all, some examples will cause crashes, and the reasons need to be investigated. I have no experience in debugging JNI, so it is difficult for me to find the real reason.

Secondly, there is a more important problem, that is GitHub Action does not currently provide CI servers on Linux ARM64 platform (https://github.com/actions/runner-images/issues/5631).

Maybe we can wait for GitHub to provide it, but it will take us several months or even years.

Another solution is cross-compilation, but it takes me more time to solve various problems, and it is more difficult. I will try to do it, but I can't provide any guarantee.

**Comment by Glavo** [comment]
This is the platform jar and jmod file I built: https://drive.google.com/drive/folders/1YCNYIokoQx3W3b_Gk4hDs-lcAm9pIG7T?usp=sharing

**Comment by Glavo** [comment]
@JakeWharton

I have completed cross-compilation adaptation. I think you can get Linux ARM64 build in the next version.

But there are still some bugs that need to be solved. I don't necessarily have time to do it. Maybe it needs the help of others.

**Comment by tonsky** [comment]
Thanks to @Glavo, Skija 0.109.2 has linux arm64 version. Let’s open separate issues if there are any issues with it
