### ISSUE TITLE
Rect size limit?

### ISSUE THREAD

**Issue by UserNameBlank** [HumbleUI/Skija#42]
I can't draw a Rect with **both** width and height over 256

Doesn't work (doesn't get drawn):
```kotlin
canvas.drawRect(Rect.makeWH(300f, 300f), paint)
```

**Comment by tonsky** [comment]
Do you have a repro? This seems very unlikely, I draw all sorts of rectangles all the time, up to 3000 at least

**Comment by UserNameBlank** [comment]
Ok, found the solution. I used LWJGL and replaced `glClear(GL.COLOR_BUFFER_BIT)` with `canvas.clear(color)` and I don't know why but it works now.
