### ISSUE TITLE
Force no antialiasing when painting / set texture filter quality?

### ISSUE THREAD

**Issue by AquilaAbriel** [HumbleUI/Skija#53]
I recently switched from SkiaSharp to Skija and so far, Skija is doing a fantastic job. 
But I encountered two dissimilarities, I could not resolve:

1. How do i "force" no antialiasing when painting. The function description states: paint.setAntiAlias() "requests" antialiasing being enabled or disabled. But in my case, it does not disable it, when I want it to. In SkiaSharp I was able to enable/disable antialiasing from one draw call to another (which was quite uesful in some scenarios) is this not possible in Skija?

2. In SkiaSharp I had the option to set a "filterQuality" state when painting a texture/image. (Which gave me the option to set nearest neighbour, bilinear, trilienar filtering) but I simply cannot find this feature in Skija. Is texture filtering handled differently in Skija? [Solved!]

**Comment by tonsky** [comment]
1. Seems to work for me. See https://github.com/HumbleUI/Skija/blob/ad625ddeadfe8bbe17a818c8028bc5005727f2e8/examples/scenes/src/WatchesScene.java#L11-L12 and the output it produces (left half no AA, right half AA):

<img width="199" alt="Screenshot 2023-04-10 at 21 54 56" src="https://user-images.githubusercontent.com/285292/230986267-f841835d-f2b6-4d27-8817-dc862f11443b.png">

I also remember it working even for stuff like clip boundaries. Maybe it depends on what and how are you drawing?

2. Take a look at https://github.com/HumbleUI/Skija/blob/ad625ddeadfe8bbe17a818c8028bc5005727f2e8/examples/scenes/src/ImagesScene.java#L55-L61. This is what it gives me:

<img width="1212" alt="Screenshot 2023-04-10 at 21 58 12" src="https://user-images.githubusercontent.com/285292/230986805-18ef76c9-edb1-4f11-8f87-8fe82c9433bb.png">

Overall I’m trying to follow Skia API as close as possible. I think if something was possible in SkiaSharp, it should be possible in Skija, too. Might be a question of convenience, though (e.g. if SkiaSharp has some composite APIs that do not directly exist in Skia)

**Comment by tonsky** [comment]
Try asking at https://groups.google.com/g/skia-discuss/? Folks there are much more familiar with Skia itself, and devs are answering questions too
