### ISSUE TITLE
[Question] Multiple windows with a shared DirectContext?

### ISSUE THREAD

**Issue by AquilaAbriel** [HumbleUI/Skija#55]
I'm currently trying to figure out how to draw to multiple windows, but with no avail.
All I could achieve so far is one window (the primary one) to render correctly, while the secondary window just displays a black screen.
I tried replicating the LWJGL example of how to run multiple GL windows simultaneously, but that wasn't really helpful:
https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/glfw/MultipleWindows.java
Mainly because the LWJGL example relies on multiple context objects (one for each window), which I would like to avoid (if possible).

Some boilerplate code of my general order of operation so far:

**Window constructor:**

```
//Set default window hints
GLFW.glfwDefaultWindowHints();

//Set window as hidden
GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GLFW.GLFW_FALSE);

//Set window resizable flag
if (resizable)
{
    GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GLFW.GLFW_TRUE);
}
else
{
    GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GLFW.GLFW_FALSE);
}

//Create GL window
boolean primaryWindow = false;
if (AEGameWindowManager.getPrimaryWindow() == null)
{
    //--> Create primary window and GL context
    windowHandle = GLFW.glfwCreateWindow(width, height, title, 0, 0);
    if (windowHandle == 0)
    {
        throw new RuntimeException("Error: Failed to create GL window");
    }
    primaryWindow = true;
}
else
{
    //--> Create secondary window, use shared context of primary window
    windowHandle = GLFW.glfwCreateWindow(width, height, title, 0, AEGameWindowManager.getPrimaryWindow().getWindowHandle());
    if (windowHandle == 0)
    {
        throw new RuntimeException("Error: Failed to create GL window");
    }
}
```

Is my assumption correct, that I have to specify the primary windows' handle as "shared" when I call glfwCreateWindow() on the secondary window creation? (If I want all my windows to use the same context as the primary window)

**Window constructor continuation:**

```
//Center window on primary screen
GLFWVidMode vidmode = GLFW.glfwGetVideoMode(GLFW.glfwGetPrimaryMonitor());
int xPos = Math.max(0, (vidmode.width() - width) / 2);
int yPos = Math.max(0, (vidmode.height() - height) / 2);
GLFW.glfwSetWindowPos(windowHandle, xPos, yPos);

//Update window dimensions
updateDimensions();

//Make window context current
GLFW.glfwMakeContextCurrent(windowHandle);

//Set v-sync state
setVSyncState(vsync);

//Unhide window
GLFW.glfwShowWindow(windowHandle);

//Initialize GL context
if (primaryWindow)
{
    initializeGLContext();
}

//Initialize GL window event callbacks
initializeGLCallbacks();

//Update SKIA resources
updateSkia();
```

**Some additional window functions:**

```
//-----------------------------------------------------------------------------------------------------//
//Initialize GL (I only have to do this once, after primary window creation?)
//-----------------------------------------------------------------------------------------------------//
private void initializeGLContext()
{
    //I have no idea what this does...
    if ("false".equals(System.getProperty("skija.staticLoad")))
    {
        Library.load();
    }
    boolean loaded = Library._loaded;

    //Create global gl context
    context = DirectContext.makeGL();
}
```

```
//-----------------------------------------------------------------------------------------------------//
//Update SKIA resources
//-----------------------------------------------------------------------------------------------------//
private void updateSkia()
{
    if (surface != null)
    {
        surface.close();
    }
    if (renderTarget != null)
    {
        renderTarget.close();
    }

    renderTarget = BackendRenderTarget.makeGL(
            frameBufferResolution.getX(),
            frameBufferResolution.getY(),
            /*msaaSamples*/0,
            /*stencil*/8,
            /*fbId*/0,
            FramebufferFormat.GR_GL_RGBA8);

    surface = Surface.makeFromBackendRenderTarget(
            context,
            renderTarget,
            SurfaceOrigin.BOTTOM_LEFT,
            SurfaceColorFormat.RGBA_8888,
            ColorSpace.getSRGB(),
            new SurfaceProps(PixelGeometry.RGB_H));
}
```

Do I have to assign an incremental framebuffer id for each backend render target? 
(I tried assigning a different id to the secondary window, but that didn't change anything.)

**Window draw():**

```
//-----------------------------------------------------------------------------------------------------//
//Draw this windows' content
//-----------------------------------------------------------------------------------------------------//
public void _draw()
{
    //Assign window to context?
    GLFW.glfwMakeContextCurrent(windowHandle);

    //Clear window surface
    //(The secondary window stays black, even if I use a different clear color...)
    surface.getCanvas().clear(0x00000000);
    
    //...Draw stuff...//

    //Swap front and back buffer
    GLFW.glfwSwapBuffers(windowHandle);
}
```

**Main loop:**

```
//Process window events
GLFW.glfwPollEvents();

AEGameWindow[] windows = AEGameWindowManager.getWindows();
for (AEGameWindow window : windows)
{
    //Draw window content
    window._draw();
}

//(Context is a static field)
AEGameWindow.getContext().flush();
```

It seems like I have to call DirectContext.flush() once each frame. But when exactly do I have to do this?
After each window was drawn, or after all windows have been drawn? 
If I do this after each window was drawn, all windows stop working and only display a black screen...

**My main question is:**
Are multiple windows even supported by Skija right now?
And if yes, Is there an order of operation, I have to comply to?
And does it matter if I have one context or multiple ones?
The only time I need to access the windows' context is when I create a new Skija Surface.
(I assume because the underlying rendertarget resource is held by the context)
But if that is the case, why can I create a new Skija Image without referencing a context?
(It's just a texture object I assume. It should be assigned to a context?)

**Comment by dzaima** [comment]
Multiple windows definitely do at least work with a separate `DirectContext.makeGL()` for each, as I have apps using that working (both with LWJGL or JWM for the window management). Can't comment on much else though, as I don't really know anything about the subject matter.

Of note is that [JWM's included Skija wrapper](https://github.com/HumbleUI/JWM/blob/5885f78119585a0551ee7cc898d01d2026ab19bc/shared/java/skija/LayerGLSkija.java#L23-L39) also makes a new `DirectContext` for each surface, and ends up creating a new one any time it's resized.

**Comment by dzaima** [comment]
> I have to say, I'm a bit surprised. When I read about OpenGL context objects I was under the impression,
> those were intended to be used very selectively and as long as the application is running.

I imagine that's more a "don't create one (or, worse, dozens) per frame without good reason" than "don't make more than one ever".

[this wiki page](https://www.khronos.org/opengl/wiki/OpenGL_Context) says

> Each context can represent a separate viewable surface, like a window in an application.

so it looks like a separate one per surface/window is the intention.

**Comment by dzaima** [comment]
Could you post the code you got to with multiple contexts? (`_draw` mainly)
