### ISSUE TITLE
how to get a canvas from Image or Bitmap

### ISSUE THREAD

**Issue by WuSanxiao** [HumbleUI/Skija#59]
i have not found a Api to to get a canvas from Image or Bitmap

**Comment by WuSanxiao** [comment]
another confusion what is the differences between Bitmap, Image, Picture and Pixmap?

**Comment by tonsky** [comment]
Canvas has ctor that accepts Bitmap.
The difference is:

- Bitmap is mutable byte array you can draw into
- Image is “GPU texture”, ready to be drawn, but not changed
- Picture is “recording of commands”, so it can be reproduced, but has no direct pixel data at all
- Pixmap, I think, is something that holds pixels for Bitmap
