### ISSUE TITLE
Java 8 doesn't work

### ISSUE THREAD

**Issue by hvven** [HumbleUI/Skija#61]
https://github.com/HumbleUI/Skija/assets/132185397/30f6de55-51e4-4a10-83a0-99b53e218c1b

Windows 11 64 bit
Temurin jdk 8 (for both gradle and project settings)

This is probably a really dumb issue, and I'm probably missing something really important. I'm really sorry if that's the case.

I saw somewhere that Java 8 is supported, but I get this error. In the video it seems like I'm using coretto 8, though I tried it again with Temurin.

The project is just a default intellij java + gradle (kotlin dsl) project, I just added this line in the main function: `Paint paint = new Paint()`

this is the `build.gradle.kts` file:
![asdf2](https://github.com/HumbleUI/Skija/assets/132185397/9fc39fe3-c143-4ca4-b041-996932b27192)

**Comment by tonsky** [comment]
Can you try it with plain javac/java? Works for me

<img width="778" alt="Screenshot 2023-09-05 at 16 01 39" src="https://github.com/HumbleUI/Skija/assets/285292/0fddbf96-c080-43f3-b144-b7b7f2d93dd2">

P.S. I wonder what makes you start new project in Java 8?

**Comment by hvven** [comment]
Thanks, that works. I can't really make with work with Gradle though, so I will try to figure it out.

**Comment by hvven** [comment]
<img width="605" alt="Screenshot 2023-09-06 at 6 29 08 PM" src="https://github.com/HumbleUI/Skija/assets/132185397/400a0da7-553a-4522-98ca-e356579189ae">
I had to include all three. Thanks so much!

**Comment by tonsky** [comment]
Weird — shared does include dependency on types, so it should be added transitively
