### ISSUE TITLE
How do we add Metal Kit Device to the surface and render

### ISSUE THREAD

**Issue by marvinh** [HumbleUI/Skija#65]
Apple has the following cpp headers available

#include <Metal/Metal.hpp>
#include <AppKit/AppKit.hpp>
#include <MetalKit/MetalKit.hpp>

is how we access metal kit device in cpp but how do we pass this the the long in skija
MTL::Device* _pDevice;

**Comment by tonsky** [comment]
I’m not sure what exactly are you asking, but does this help?

https://github.com/HumbleUI/JWM/blob/a04867c5f45b126caafe9abccd9ecd00d3bc516f/macos/java/LayerMetal.java#L62-L65
https://github.com/HumbleUI/JWM/blob/a04867c5f45b126caafe9abccd9ecd00d3bc516f/macos/java/skija/LayerMetalSkija.java#L19
https://github.com/HumbleUI/Skija/blob/a63330f37f24d57b457e625d861b121689c8d182/shared/java/DirectContext.java#L16

**Comment by marvinh** [comment]
Yes thank you this is exactly it ! is their a way to view the api without looking at source code ?

**Comment by tonsky** [comment]
Not really
